version: '3'
services:

  app:
    build: ./
    command: sh -c "symfony server:stop && symfony server:start --port=4090"
    environment:
      APP_DEBUG: 1
    volumes:
      - "./:/app"
      - "composer:/root/composer"
    expose:
      - 4090
    ports:
      - "4090:4090"

volumes:
  composer: null